"""
Pre-seeded representative company opportunities for demo verification.
Marked with DEMO_DATA source status.
"""

from .models import JobPosting, SourceStatus
from .dedupe import job_fingerprint

def _mk(company_id, company, title, url, location, etype, req, pref, desc=""):
    jid = job_fingerprint(company_id, title, location, url, None)
    return JobPosting(
        id=jid,
        company=company,
        company_id=company_id,
        title=title,
        official_url=url,
        application_url=url,
        location=location,
        work_mode="Hybrid",
        employment_type=etype,
        required_skills=req,
        preferred_skills=pref,
        description=desc,
        source_type="demo",
        source_status=SourceStatus.DEMO_DATA,
    )

def build_demo_jobs():
    return [
        _mk("google", "Google", "Software Engineering Intern",
            "https://careers.google.com/jobs/results/", "Bangalore, India", "Internship",
            ["DSA", "Python", "C++", "System Design"], ["Machine Learning", "Go"],
            "Software Engineering Internship working on core infrastructure at Google."),
        _mk("google", "Google", "Data Science & Analytics Intern",
            "https://careers.google.com/jobs/results/", "Hyderabad, India", "Internship",
            ["Python", "Statistics", "Machine Learning", "SQL"], ["Deep Learning", "Pandas"],
            "Data Science internship applying predictive modeling at Google scale."),
        _mk("nvidia", "NVIDIA", "Machine Learning & AI Intern",
            "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite", "Pune, India", "Internship",
            ["Python", "Machine Learning", "Deep Learning", "Statistics"], ["PyTorch", "CUDA", "Docker"],
            "Deep learning research internship at NVIDIA."),
        _mk("nvidia", "NVIDIA", "Systems Software Engineer Intern",
            "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite", "Bangalore, India", "Internship",
            ["C++", "DSA", "Operating Systems", "Linux"], ["Computer Networks", "OOP"],
            "Systems kernel and compiler acceleration internship at NVIDIA."),
        _mk("microsoft", "Microsoft", "Software Engineer Intern (SDE)",
            "https://jobs.careers.microsoft.com/global/en/search", "Hyderabad, India", "Internship",
            ["DSA", "C++", "Java", "OOP"], ["System Design", "Azure", "REST APIs"],
            "SWE Intern role at Microsoft India Development Center."),
        _mk("microsoft", "Microsoft", "Cloud Solutions Analyst",
            "https://jobs.careers.microsoft.com/global/en/search", "Noida, India", "Full-time",
            ["AWS", "Linux", "SQL", "Communication"], ["Docker", "Kubernetes", "CI/CD"],
            "Cloud Solutions Analyst at Microsoft Azure enterprise division."),
        _mk("amazon", "Amazon", "Software Development Engineer (SDE-1)",
            "https://www.amazon.jobs/en/", "Bangalore, India", "Full-time",
            ["DSA", "Java", "Python", "System Design", "OOP"], ["AWS", "Microservices"],
            "SDE-1 role building scalable high-throughput services at Amazon."),
        _mk("amazon", "Amazon", "Business Intelligence Analyst",
            "https://www.amazon.jobs/en/", "Hyderabad, India", "Full-time",
            ["SQL", "Python", "Data Visualization", "Communication"], ["Statistics", "Pandas"],
            "Business Analyst evaluating fulfillment center supply-chain efficiency."),
        _mk("infosys", "Infosys", "Systems Engineer",
            "https://www.infosys.com/careers/", "Multiple, India", "Full-time",
            ["Java", "SQL", "Communication", "Problem Solving"], ["Spring Boot", "REST APIs"],
            "Campus recruitment Systems Engineer role at Infosys."),
        _mk("infosys", "Infosys", "Specialist Programmer (Power Programmer)",
            "https://www.infosys.com/careers/", "Bangalore, India", "Full-time",
            ["DSA", "Java", "System Design", "OOP"], ["Microservices", "Docker", "AWS"],
            "High-package competitive coding track at Infosys."),
        _mk("tcs", "TCS", "Digital Developer (Ninja & Digital Track)",
            "https://www.tcs.com/careers", "Mumbai, India", "Full-time",
            ["Java", "SQL", "Communication", "Python"], ["Spring Boot", "Docker", "Git"],
            "TCS Digital role for high-performing engineering graduates."),
        _mk("tcs", "TCS", "Data & AI Associate",
            "https://www.tcs.com/careers", "Chennai, India", "Full-time",
            ["Python", "SQL", "Machine Learning", "Data Visualization"], ["AWS", "Pandas"],
            "Data & AI team associate at TCS."),
        _mk("wipro", "Wipro", "Project Engineer (Turbo / Elite)",
            "https://careers.wipro.com/", "Pune, India", "Full-time",
            ["Java", "SQL", "Communication", "Problem Solving"], ["Spring Boot", "Git"],
            "Project Engineer campus hiring track at Wipro."),
        _mk("accenture", "Accenture", "Associate Software Engineer (ASE)",
            "https://www.accenture.com/in-en/careers", "Bangalore, India", "Full-time",
            ["Java", "SQL", "Communication", "REST APIs"], ["Git", "Cloud"],
            "ASE role at Accenture Technology India."),
        _mk("ibm", "IBM", "Associate Cloud Developer",
            "https://www.ibm.com/careers/", "Kochi, India", "Full-time",
            ["Java", "SQL", "REST APIs", "Linux"], ["Docker", "Kubernetes", "Microservices"],
            "Cloud application developer role at IBM Software Labs."),
        _mk("oracle", "Oracle", "Associate Software Engineer - Database Cloud",
            "https://www.oracle.com/careers/", "Hyderabad, India", "Full-time",
            ["Java", "SQL", "DSA", "OOP"], ["Spring Boot", "Linux", "DBMS"],
            "ASE role working on Oracle Cloud Infrastructure and DB engines."),
        _mk("deloitte", "Deloitte", "Technology Analyst - Systems & Cloud",
            "https://www2.deloitte.com/in/en/careers.html", "Gurugram, India", "Full-time",
            ["SQL", "Python", "Communication", "Data Visualization"], ["Statistics", "AWS"],
            "Technology Analyst role in Deloitte USI consulting practice.")
    ]
